### ISSUE TITLE
Support alpha to hex

### ISSUE THREAD

**Issue by sacru2red** [iamlite/color-core#22]
Generally, hex color is used as 3 or 6 digits, but it can be used by adding 2-digits meaning alpha.
https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color

current:
```ts
new Color('4aa444').setAlhap(0.5).toHex()
```
returns the same value as 4aa444.

I would like to add a method like toHex8() to returnvalue that includes the alpha value.

**Comment by iamlite** [comment]
Thank you for pointing this out. ill work on it.

**Comment by iamlite** [comment]
Fixed in 1.4.0
